version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"        
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run start:dev 
    restart: always         
    logging:
      driver: "json-file"   
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:14      
    restart: always         
    environment:
      POSTGRES_USER: ${DB_USERNAME}  
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s         
      timeout: 5s           
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pgdata:
