# FXQL Validation Rules Configuration
# Version: 1.0.0
# Last Updated: 2025-10-18

version: "1.0.0"

currencies:
  # ISO 4217 Currency Codes - Supported by FXQL Parser
  valid_codes:
    - AFN
    - ALL
    - DZD
    - USD
    - EUR
    - AOA
    - XCD
    - ARS
    - AMD
    - AWG
    - AUD
    - AZN
    - BSD
    - BHD
    - BDT
    - BBD
    - BYN
    - BZD
    - XOF
    - BMD
    - BTN
    - INR
    - BOB
    - BOV
    - BAM
    - BWP
    - NOK
    - BRL
    - BND
    - BGN
    - BIF
    - CVE
    - KHR
    - XAF
    - CAD
    - KYD
    - CLF
    - CLP
    - CNY
    - COP
    - COU
    - KMF
    - CDF
    - NZD
    - CRC
    - CUC
    - CUP
    - ANG
    - CZK
    - DKK
    - DJF
    - DOP
    - EGP
    - SVC
    - ERN
    - ETB
    - FKP
    - FJD
    - XPF
    - GMD
    - GEL
    - GHS
    - GIP
    - GTQ
    - GBP
    - GNF
    - GYD
    - HTG
    - HNL
    - HKD
    - HUF
    - ISK
    - IDR
    - XDR
    - IRR
    - IQD
    - ILS
    - JMD
    - JPY
    - JOD
    - KZT
    - KES
    - KPW
    - KRW
    - KWD
    - KGS
    - LAK
    - LBP
    - LSL
    - LRD
    - LYD
    - CHF
    - MOP
    - MGA
    - MWK
    - MYR
    - MVR
    - MRU
    - MUR
    - MXN
    - MDL
    - MNT
    - MAD
    - MZN
    - MMK
    - NAD
    - NPR
    - NGN
    - OMR
    - PKR
    - PAB
    - PGK
    - PYG
    - PEN
    - PHP
    - PLN
    - QAR
    - MKD
    - RON
    - RUB
    - RWF
    - SHP
    - WST
    - STN
    - SAR
    - RSD
    - SCR
    - SLE
    - SGD
    - SBD
    - SOS
    - SSP
    - LKR
    - SDG
    - SRD
    - SZL
    - SEK
    - CHE
    - CHW
    - SYP
    - TWD
    - TJS
    - TZS
    - THB
    - TOP
    - TTD
    - TND
    - TRY
    - TMT
    - UGX
    - UAH
    - AED
    - UYI
    - UYU
    - UZS
    - VUV
    - VED
    - VND
    - ZMW
    - ZWL

business_rules:
  max_currency_pairs_per_request: 1000
  min_price: 0
  max_price: 999999999
  min_cap_amount: 0
  max_cap_amount: 2147483647
  
rate_limits:
  default_ttl_seconds: 60
  default_limit: 10
